[project]
name = "utility-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.27.1",
    "python-pptx>=1.0.2",
    "sherpa-onnx>=1.12.25",
]
